services:
  db:
    image: postgres:17.2
    environment:
      POSTGRES_DB: auction_db
      POSTGRES_USER: auction
      POSTGRES_PASSWORD: auction
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U auction -d auction_db"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  postgres_data:
